export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';

export const DOWNLOADING_PRODUCTS = 'DOWNLOADING_PRODUCTS';
export const DOWNLOADING_PRODUCTS_SUCCESS = 'DOWNLOADING_PRODUCTS_SUCCESS';
export const DOWNLOADING_PRODUCTS_ERROR = 'DOWNLOADING_PRODUCTS_ERROR';
