export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';

export const DOWNLOADING_PRODUCTS = 'DOWNLOADING_PRODUCTS';
export const DOWNLOADING_PRODUCTS_SUCCESS = 'DOWNLOADING_PRODUCTS_SUCCESS';
export const DOWNLOADING_PRODUCTS_ERROR = 'DOWNLOADING_PRODUCTS_ERROR';

export const GET_PRODUCT_TO_REMOVE = 'GET_PRODUCT_TO_REMOVE';
export const GET_PRODUCT_TO_REMOVE_SUCCESS = 'GET_PRODUCT_TO_REMOVE_SUCCESS';
export const GET_PRODUCT_TO_REMOVE_ERROR = 'GET_PRODUCT_TO_REMOVE_ERROR';

export const GET_PRODUCT_TO_UPDATE = 'GET_PRODUCT_TO_UPDATE';
export const GET_PRODUCT_TO_UPDATE_START = 'GET_PRODUCT_TO_UPDATE_START';
export const GET_PRODUCT_TO_UPDATE_SUCCESS = 'GET_PRODUCT_TO_UPDATE_SUCCESS';
export const GET_PRODUCT_TO_UPDATE_ERROR = 'GET_PRODUCT_TO_UPDATE_ERROR';
